services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/keycloak`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_FEATURES: token-exchange,admin-fine-grained-authz:v1

      KC_HOSTNAME: 04f7-81-240-46-212.ngrok-free.app
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /keycloak
    ports:
      - "8080:8080"

  mcp_server:
    image: mcp-server:1.0.0
    container_name: mcp_server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp.rule=PathPrefix(`/`)"
      - "traefik.http.services.mcp.loadbalancer.server.port=9000"
    environment:
      ISSUER_URI: https://04f7-81-240-46-212.ngrok-free.app/keycloak/realms/demo-mcp-servers
      TEMPERATURE_API: https://04f7-81-240-46-212.ngrok-free.app/api
      TOKEN_EXCHANGE_CLIENT_ID: token-exchange
      TOKEN_EXCHANGE_CLIENT_SECRET: e37af147-ebef-4723-be20-0ba92bc25b08
    ports:
      - "9000:9000"
    depends_on:
      - keycloak

  temperature_api:
    image: temperature-api:1.0.0
    container_name: temperature_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
      - "traefik.http.services.api.loadbalancer.server.port=9999"
    environment:
      ISSUER_URI: https://04f7-81-240-46-212.ngrok-free.app/keycloak/realms/demo-users
    ports:
      - "9999:9999"
    depends_on:
      - keycloak

  traefik:
    image: traefik:v3.0
    container_name: proxy
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock