services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/keycloak`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_HOSTNAME: 3022b8352db3.ngrok-free.app
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /keycloak
    ports:
      - "8080:8080"

  mcp_server:
    image: ghcr.io/nicholasm95/secure-mcp-server:1.0.0
    container_name: mcp_server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp.rule=PathPrefix(`/`)"
      - "traefik.http.services.mcp.loadbalancer.server.port=9000"
    environment:
      ISSUER_URI: https://3022b8352db3.ngrok-free.app/keycloak/realms/demo-dcr
    ports:
      - "9000:9000"
    depends_on:
      - keycloak

  traefik:
    image: traefik:v3.0
    container_name: proxy
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock