server:
  port: 9000


spring:
  application:
    name: demo-mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: demo-mcp-server
        version: 1.0.0
        type: SYNC
        annotation-scanner:
          enabled: true
        protocol: STREAMABLE

issuer-uri: ${ISSUER_URI}
temperature.api: ${TEMPERATURE_API}